# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    source_url: http://lattecake.dev/uploads/
    source_url: http://source.lattecake.com/
    storage_url: http://storage.lattecake.com/
    admin_static: http://demo.lattecake.com/Template/ACE/
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
