# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    source_url: http://lattecake.dev/uploads/
    source_url: http://source.lattecake.com/
    storage_url: http://storage.lattecake.com/
    admin_static: http://demo.lattecake.com/Template/ACE/
    duoshuo_api: http://api.duoshuo.com/

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: AppBundle:Pagination:sliding.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    fos_user.doctrine_registry:
        alias: doctrine

    app.response_listener:
        class: AppBundle\EventListener\ResponseListener
        arguments: ["@logger"]
        tags:
            - { name: kernel.event_listener, event: kernel.controller }
            - { name: kernel.event_listener, event: kernel.response }