<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{

    /**
     * 获取最火的几片文章
     * @return array
     */
    public function findPostsTop()
    {
        return $this->_em->createQueryBuilder()
            ->select("p")
            ->from("AppBundle:Post", "p")
            ->setMaxResults( 3 )
            ->orderBy("p.id", 'DESC')
            ->getQuery()->getResult();
    }

    /**
     * 获取文章列表
     * @param int $page
     * @return array
     */
    public function findPostsPage( $page = 1 )
    {
        return $this->_em->createQueryBuilder()
            ->select("p")
            ->from("AppBundle:Post", "p")
            ->setMaxResults( 10 )
            ->setFirstResult( ($page - 1) * 10 )
            ->orderBy("p.id", 'DESC')
            ->getQuery()->getResult();
    }

    /**
     * 统计文章数量
     * @return mixed
     */
    public function countPosts()
    {
        return $this->_em->createQueryBuilder()
            ->select("COUNT(p.id)")
            ->from("AppBundle:post", "p")
            ->getQuery()->getSingleScalarResult();
    }
}
