<?php

namespace StoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * 统计所有分类数量
     * @return mixed
     */
    public function countCategoryAll()
    {
        return $this->_em->createQueryBuilder()
            ->select("COUNT(c.id)")
            ->from('StoreBundle:Category', 'c')
            ->getQuery()->getSingleScalarResult();
    }
}
