<?php

namespace StoreBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    /**
     * 根据分页查找图片
     * @param int $page
     * @return array
     */
    public function findImagesByPage( $page = 1 )
    {
        return $this->_em->createQueryBuilder()
            ->select("i")
            ->from('StoreBundle:Image', 'i')
            ->getQuery()->getResult();
    }
}
